import { visit } from "unist-util-visit"
import type { Root, Element } from "hast"
import * as fs from "fs"
import * as path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

interface Dimensions {
  width: number
  height: number
}

/**
 * Intrinsic image dimensions, generated by prebuild (public/image-dimensions.json),
 * keyed by resolved /content/Media/... path. Loaded once at build time; missing
 * file just means no dimensions are injected (no CLS fix, but nothing breaks).
 */
let dimensionsCache: Record<string, Dimensions> | null = null

function loadDimensions(): Record<string, Dimensions> {
  if (dimensionsCache) return dimensionsCache
  try {
    const manifestPath = path.resolve(__dirname, "../../public/image-dimensions.json")
    dimensionsCache = JSON.parse(fs.readFileSync(manifestPath, "utf-8")) as Record<string, Dimensions>
  } catch {
    dimensionsCache = {}
  }
  return dimensionsCache
}

/**
 * Rehype plugin that transforms relative image paths to /content/Media/ and
 * stamps intrinsic width/height so the browser can reserve layout space
 * (eliminates Cumulative Layout Shift). Author-supplied width/height are kept.
 */
export function rehypeImagePaths() {
  const dimensions = loadDimensions()

  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName === "img" && node.properties) {
        const src = node.properties.src as string
        if (src && !src.startsWith("http") && !src.startsWith("/") && !src.startsWith("data:")) {
          const stripped = src.replace(/^[Mm]edia\//, "")
          node.properties.src = `/content/Media/${stripped}`
        }

        // Reserve layout space from the intrinsic size. Skip SVGs (no fixed
        // intrinsic box) and anything the author already dimensioned. The global
        // `img { max-width:100%; height:auto }` keeps it responsive — the attrs
        // only fix the aspect ratio so nothing reflows once the image loads.
        const resolvedSrc = node.properties.src as string
        const dims = dimensions[resolvedSrc]
        const hasAuthorSize =
          node.properties.width != null || node.properties.height != null
        if (dims && !hasAuthorSize && !resolvedSrc.endsWith(".svg")) {
          node.properties.width = dims.width
          node.properties.height = dims.height
        }
      }
    })
  }
}
